Update locals.tf to include A record for beta.
BanklessDAO/infrastructure pull request #25
Opened 2023-09-06 19:32 UTC by tomtranmer

Purpose
-------
added record for beta.banklesscard.xyz -> tws servers for testing

Changes Made
------------
Added an A record to reference staging server at 172.105.3.37 for the URL beta.banklesscard.xyz

No changes to main domain or URL.

2023-09-06 20:08 UTC, BogDrakonov requested changes
Can you try running `terraform fmt` to fix formatting? I recommend following the repo docs to install pre-commit as well locally.

Any particular reason you're not using the Cloudflare proxy? It's exceptionally useful, especially when pointed at a single server.

2023-09-06 20:33 UTC, tomtranmer commented
Sure thing,

What’s the procedure, or link for that; it’s new to me?

I’m just trying the first thing that I thought would work.

Cheers,

Tom Tranmer

> On Sep 6, 2023, at 4:08 PM, BogDrakonov ***@***.***> wrote:
> 
> 
> @BogDrakonov requested changes on this pull request.
> 
> Can you try running terraform fmt to fix formatting? I recommend following the repo docs to install pre-commit as well locally.
> 
> Any particular reason you're not using the Cloudflare proxy? It's exceptionally useful, especially when pointed at a single server.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/BanklessDAO/infrastructure/pull/25#pullrequestreview-1614129279>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAM437A4HJKI2SYREADES2TXZDJ23ANCNFSM6AAAAAA4N2HFBE>.
> You are receiving this because you authored the thread.
>

2023-10-24 18:03 UTC, BogDrakonov commented
@tomtranmer Do you mind running `terraform fmt` on your code? It's helpful to `pre-commit install` locally to make sure your code matches our requirements.
One more thing. I highly recommend enabling the Cloudflare proxy to protect our resources from DDoS and basic security attacks

2023-11-14 18:43 UTC, BogDrakonov commented
@tomtranmer Do you need help with this or is this PR abandonded?

2023-12-08 20:34 UTC, closed without merging