feat: deploy bankless.community to cloudflare pages
BanklessDAO/infrastructure pull request #26
Opened 2023-10-05 13:10 UTC by MantisClone

Changes
------------

* feat: add bankless.community pages config based on https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_project

2023-10-05 14:13 UTC, mklebrasseur commented on bankless-community/cloudflare/pages.tf
Secrets should not be provided in the repo, they should be placed within the BanklessDAO Bitwarden and then InfoSec will add them as secret ENV's. You can reference them in this project as variables and expect that Terraform Cloud will fill them in.

Example
`variable "alchemy_api_key" {
  sensitive = true
}`

2023-10-05 14:14 UTC, mklebrasseur requested changes
**Requirements**
- Rotate Secrets
- Replace Secrets with Sensitive Variables
- Add Secrets to Bitwarden
- Add Secrets to Terraform Cloud

2023-10-05 14:16 UTC, MantisClone commented on bankless-community/cloudflare/pages.tf
Okay :+1: 

FYI, the current secrets are long-burned and all free accounts so it doesn't matter *that* much, but I will do as you've requested anyway.

2023-10-05 14:17 UTC, MantisClone commented on bankless-community/cloudflare/pages.tf
@mklebrasseur Can you please grant me access to the BanklessDAO Bitwarden with appropriate access control? My email is david.hunt-mateo@mantisdata.solutions.

2023-10-05 14:18 UTC, BogDrakonov requested changes
We need to delete and rotate the secrets committed. This is a public repo, but this is bad practice even in private repos.

As @mklebrasseur said
```
Secrets should not be provided in the repo, they should be placed within the BanklessDAO Bitwarden and then InfoSec will add them as secret ENV's. You can reference them in this project as variables and expect that Terraform Cloud will fill them in.

Example
variable "alchemy_api_key" { sensitive = true }
```

2023-10-05 14:18 UTC, BogDrakonov commented on README.md
> -This repo uses Yelp's [pre-commit](https://pre-commit.com/) to manage some pre-commit hooks automatically.
Why are we adjusting the main README on the repo?

2023-10-05 14:18 UTC, BogDrakonov commented on bankless-community/cloudflare/pages.tf
> +        NEXT_PUBLIC_ALCHEMY_API_KEY          = "xoSmxF5VP5yJq0zV-MedaxZUCYSt7DUN"
Let's get these secrets deleted and rotated ASAP

2023-10-05 14:32 UTC, MantisClone commented on README.md
> -This repo uses Yelp's [pre-commit](https://pre-commit.com/) to manage some pre-commit hooks automatically.
This is because the instructions were incorrect. They said to use `make` to setup the pre-commit hooks but no makefile exists.

I updated the README to explain how to configure pre-commit directly.

2023-10-05 14:37 UTC, MantisClone commented on .gitignore
> +venv/
I added this because I used python and pip to install pre-commit

2023-10-05 14:38 UTC, MantisClone commented on bankless-community/cloudflare/pages.tf
Done :white_check_mark:

2023-10-05 14:39 UTC, MantisClone commented on bankless-community/cloudflare/pages.tf
> +        NEXT_PUBLIC_ALCHEMY_API_KEY          = "xoSmxF5VP5yJq0zV-MedaxZUCYSt7DUN"
Done :white_check_mark:

2023-10-09 16:45 UTC, MantisClone commented
@BogDrakonov @mklebrasseur 
I rotated the API keys and added them to [Bitwarden](https://vault.banklesscard.xyz/#/organizations/678938b7-ebd5-4cd4-ba0f-31e490bdcdbd/vault?collectionId=c7a3b2bd-52e6-4362-bd48-bc761b3f435a).

For now, the API keys are associated with my personal accounts - to solve the current API key leak.

In the future, I think it would be appropriate to create dedicated BanklessDAO accounts and generate the API keys from them instead of my personal accounts. The credentials for these dedicated accounts could be stored in Bitwarden and shared as needed.

![image](https://github.com/BanklessDAO/infrastructure/assets/2530913/6c6a6f38-c33c-4c5a-8101-0540547872fc)

2023-10-16 13:45 UTC, MantisClone commented
Hello @BogDrakonov @mklebrasseur How'd it go? Have you successfully added the secrets to the Terraform cloud?

2023-10-16 14:11 UTC, mklebrasseur requested changes

2023-10-16 14:11 UTC, mklebrasseur commented on bankless-community/cloudflare/pages.tf
> +variable "walletconnect_project_id" { sensitive = true }
Please move the variables to variables.tf please.

2023-10-16 14:12 UTC, mklebrasseur commented
> Hello @BogDrakonov @mklebrasseur How'd it go? Have you successfully added the secrets to the Terraform cloud?

Completed, requested the move of the variables to the variables file. Other than that it's good to go!

2023-10-17 12:36 UTC, mklebrasseur submitted a review, later dismissed

2023-10-22 17:51 UTC, MantisClone commented
@BogDrakonov I'd like to get this deployed and the domain switched over before the end of October so I don't need to seek reimbursement for Vercel hosting in November.

2023-10-24 18:08 UTC, BogDrakonov commented
I'm sorry we didn't catch this earlier, but do you mind opening a PR as a feature branch on this repo? Opening a PR from an external repo doesn't trigger a Terraform plan so we can't validate the result and merge it. Do you mind opening a PR from within this repo? All BanklessDAO GH members have write access to the repo

2023-10-24 18:08 UTC, BogDrakonov requested changes

2023-10-24 18:08 UTC, BogDrakonov commented on bankless-community/cloudflare/pages.tf
> +        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = walletconnect_project_id
It looks like the variables are not specified correctly. It would be `var.var_name` not just `var_name`

2023-10-24 19:18 UTC, MantisClone commented on bankless-community/cloudflare/pages.tf
> +        NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = walletconnect_project_id
Fixed. :white_check_mark:

2023-10-24 19:23 UTC, MantisClone commented
Superseded by https://github.com/BanklessDAO/infrastructure/pull/27

2023-10-24 19:23 UTC, closed without merging